### ISSUE TITLE
Bubble Bobble Ultra MRA Update

### ISSUE THREAD

**Issue by OngoGablogian** [dyreschlock/pocket-extras#18]
Hello,

I was the one who provided the Bubble Bobble Ultra MRA over on the FPGAming discord when the core first launched on Pocket. Due to today's updates to the jtbubl core, the MRA needed to be updated as well. I've attached the new MRA as well as the necessary .json files to this issue.

Also, this MRA file will patch the ROM so creating a separate ZIP file with the patched MAME ROMs isn't necessary. Just run the MRA tool with the standard merged MAME ROM and you're good to go.

Thanks.

[Bubble Bobble Ultra [v1.0].zip](https://github.com/dyreschlock/pocket-extras/files/13620243/Bubble.Bobble.Ultra.v1.0.zip)

**Comment by dyreschlock** [comment]
Thanks a lot!  Everything is working after the update.  I'll make a new release with this included.

**Comment by dyreschlock** [comment]
Over the weekend, Jotego released many changes in jtbin, including the Bobble Bubble. The MRA changed as a result. Besides default Mister button changes at the bottom, line 41 was changed.

Previous: `<part> 00 00 </part>`
Current: `<part> 00 00 00 00 </part>`

This comes at the beginning of the rom description. This adds an extra byte or two or four at the beginning of the rom? Because of this, all of your patch work in the Bubble Bobble Ultra MRA is misaligned, and no longer runs on the Pocket.

Could you take a look at this and update the MRA?

**Comment by OngoGablogian** [comment]
Thanks for letting me know. I've attached the updated MRA and the other files required for the Pocket. If there are any issues let me know.
[Bubble Bobble Ultra [v1.0] (20240129).zip](https://github.com/dyreschlock/pocket-extras/files/14088029/Bubble.Bobble.Ultra.v1.0.20240129.zip)

**Comment by dyreschlock** [comment]
Thank you so much!  Everything works again :)
