### ISSUE TITLE
Donkey Kong Jr. doesn't appear to be compatible with Eric Lewis' DK core

### ISSUE THREAD

**Issue by YLFAndy** [dyreschlock/pocket-extras#5]
DKJr locks at boot and plays some corrupted sound on loop. I've verified on two Pockets.

Steps:
1. Install the pocket-extras packages on the Pocket in appropriate folders.
2. Run the retrodriven updater OR create a dkongjr rom from an appropriate zip/MRA using a tool like Orca.
3. Launch the Donkey Kong core
4. Select Donkey Kong Junior

Result:
The loading bar completes, then the screen goes black and some corrupted music plays on loop.

Expected:
The rom to not be included ( I believe the DK board requires a second sound processor and extra memory) or to load.

**Comment by dyreschlock** [comment]
Ah ok.  I'll take a look.

The description of the core said that it didn't work, but I had the JSON in my "it works" folder from a while ago, so I assumed it was good.

**Comment by YLFAndy** [comment]
No worries, I figured it slipped through. Thanks!

**Comment by dyreschlock** [comment]
Yeah, it's definitely broken.  I could've sworn that it worked at some point though.

Sometimes when you run cores, quit out of them, and run a different core, artifacts are left on the FPGA because certain sectors weren't cleaned up. I think when I was initially testing them, I ran another core first that initiated the sectors required for Donkey Kong Jr.  I tried out a couple core combinations, but I still couldn't get it to work.

Anyways, I removed that JSON and the JSON from another game that didn't work either.

Thanks for the catch. :)
