### ISSUE TITLE
The Punisher no longer working with latest CPS2 core

### ISSUE THREAD

**Issue by KClough** [dyreschlock/pocket-extras#9]
I'm not sure if this is an issue with the MRA file or if something reverted with Jotego's core. 

It worked previously, but now I'm getting a black screen after the rom is loaded.

**Comment by dyreschlock** [comment]
I've been too busy to look into this, but some news came up on the FPGA discord today.

Apparently the Updater archive was updated to use the CPS1.5 version of the rom rather than the CPS2 conversion which is used here. There's no MRA file for the CPS2 conversion because it was hacked together after the fact.

If you use an Updater (RetroDriven, Matt Panella, or Pockey Sync), you should be able to get the updated rom that should work.

**Comment by dyreschlock** [comment]
To add to this.  

The Punisher JSON for CPS2 here has the same rom name as the CPS1.5 version, thus creating a name collision in the Updater rom archive.  The CPS2 Rom should have a different name.

**Comment by dyreschlock** [comment]
This is working now.  The updaters just need the roms.
